//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinamentoWebService.Automation.VendaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NfseReponse", Namespace="http://schemas.datacontract.org/2004/07/TreinamentoServiceApp.Contract")]
    [System.SerializableAttribute()]
    public partial class NfseReponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreinamentoWebService.Automation.VendaService.Nfse NfseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreinamentoWebService.Automation.VendaService.Nfse Nfse {
            get {
                return this.NfseField;
            }
            set {
                if ((object.ReferenceEquals(this.NfseField, value) != true)) {
                    this.NfseField = value;
                    this.RaisePropertyChanged("Nfse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nfse", Namespace="http://schemas.datacontract.org/2004/07/TreinamentoServiceApp.Contract")]
    [System.SerializableAttribute()]
    public partial class Nfse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoVerificacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEmissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreinamentoWebService.Automation.VendaService.Servico ServicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoVerificacao {
            get {
                return this.CodigoVerificacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoVerificacaoField, value) != true)) {
                    this.CodigoVerificacaoField = value;
                    this.RaisePropertyChanged("CodigoVerificacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEmissao {
            get {
                return this.DataEmissaoField;
            }
            set {
                if ((this.DataEmissaoField.Equals(value) != true)) {
                    this.DataEmissaoField = value;
                    this.RaisePropertyChanged("DataEmissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreinamentoWebService.Automation.VendaService.Servico Servico {
            get {
                return this.ServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicoField, value) != true)) {
                    this.ServicoField = value;
                    this.RaisePropertyChanged("Servico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servico", Namespace="http://schemas.datacontract.org/2004/07/TreinamentoServiceApp.Contract")]
    [System.SerializableAttribute()]
    public partial class Servico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscriminacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TreinamentoWebService.Automation.VendaService.Valores ValoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Discriminacao {
            get {
                return this.DiscriminacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscriminacaoField, value) != true)) {
                    this.DiscriminacaoField = value;
                    this.RaisePropertyChanged("Discriminacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TreinamentoWebService.Automation.VendaService.Valores Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Valores", Namespace="http://schemas.datacontract.org/2004/07/TreinamentoServiceApp.Contract")]
    [System.SerializableAttribute()]
    public partial class Valores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorLiquidoNfseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorServicosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorLiquidoNfse {
            get {
                return this.ValorLiquidoNfseField;
            }
            set {
                if ((this.ValorLiquidoNfseField.Equals(value) != true)) {
                    this.ValorLiquidoNfseField = value;
                    this.RaisePropertyChanged("ValorLiquidoNfse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorServicos {
            get {
                return this.ValorServicosField;
            }
            set {
                if ((this.ValorServicosField.Equals(value) != true)) {
                    this.ValorServicosField = value;
                    this.RaisePropertyChanged("ValorServicos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venda", Namespace="http://schemas.datacontract.org/2004/07/TreinamentoServiceApp.Contract")]
    [System.SerializableAttribute()]
    public partial class Venda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NfseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nfse {
            get {
                return this.NfseField;
            }
            set {
                if ((object.ReferenceEquals(this.NfseField, value) != true)) {
                    this.NfseField = value;
                    this.RaisePropertyChanged("Nfse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VendaService.IVendaService")]
    public interface IVendaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendaService/GetNfse", ReplyAction="http://tempuri.org/IVendaService/GetNfseResponse")]
        TreinamentoWebService.Automation.VendaService.NfseReponse GetNfse(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendaService/GetNfse", ReplyAction="http://tempuri.org/IVendaService/GetNfseResponse")]
        System.Threading.Tasks.Task<TreinamentoWebService.Automation.VendaService.NfseReponse> GetNfseAsync(string numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendaService/GetVenda", ReplyAction="http://tempuri.org/IVendaService/GetVendaResponse")]
        TreinamentoWebService.Automation.VendaService.Venda GetVenda(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVendaService/GetVenda", ReplyAction="http://tempuri.org/IVendaService/GetVendaResponse")]
        System.Threading.Tasks.Task<TreinamentoWebService.Automation.VendaService.Venda> GetVendaAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVendaServiceChannel : TreinamentoWebService.Automation.VendaService.IVendaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendaServiceClient : System.ServiceModel.ClientBase<TreinamentoWebService.Automation.VendaService.IVendaService>, TreinamentoWebService.Automation.VendaService.IVendaService {
        
        public VendaServiceClient() {
        }
        
        public VendaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TreinamentoWebService.Automation.VendaService.NfseReponse GetNfse(string numero) {
            return base.Channel.GetNfse(numero);
        }
        
        public System.Threading.Tasks.Task<TreinamentoWebService.Automation.VendaService.NfseReponse> GetNfseAsync(string numero) {
            return base.Channel.GetNfseAsync(numero);
        }
        
        public TreinamentoWebService.Automation.VendaService.Venda GetVenda(int id) {
            return base.Channel.GetVenda(id);
        }
        
        public System.Threading.Tasks.Task<TreinamentoWebService.Automation.VendaService.Venda> GetVendaAsync(int id) {
            return base.Channel.GetVendaAsync(id);
        }
    }
}
